### ISSUE TITLE
jre/jdk8 fails to load with java.lang.InternalError

### ISSUE THREAD

**Issue by thirdwheel** [Zlika/tce#2]
Hi

Trying to use tinycore 11.1 to run a Minecraft server and this is the error I get:

    minecraft@mc-creative-01:/home/minecraft$ $JAVA_HOME/bin/java -jar minecraft-server_1.15.2.jar
    Exception in thread "main" java.lang.InternalError: Unsupported Management version
    	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
    	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
    	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    	at java.lang.System.loadLibrary(System.java:1122)
    	at sun.management.ManagementFactoryHelper$4.run(ManagementFactoryHelper.java:451)
    	at sun.management.ManagementFactoryHelper$4.run(ManagementFactoryHelper.java:449)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at sun.management.ManagementFactoryHelper.<clinit>(ManagementFactoryHelper.java:448)
    	at java.lang.management.ManagementFactory.getRuntimeMXBean(ManagementFactory.java:350)
    	at org.apache.logging.log4j.core.lookup.JmxRuntimeInputArgumentsLookup.<clinit>(JmxRuntimeInputArgumentsLookup.java:35)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    	at org.apache.logging.log4j.util.LoaderUtil.newInstanceOf(LoaderUtil.java:158)
    	at org.apache.logging.log4j.util.LoaderUtil.newInstanceOf(LoaderUtil.java:180)
    	at org.apache.logging.log4j.util.LoaderUtil.newCheckedInstanceOf(LoaderUtil.java:201)
    	at org.apache.logging.log4j.core.util.Loader.newCheckedInstanceOf(Loader.java:300)
    	at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:110)
    	at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:125)
    	at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
    	at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:77)
    	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:171)
    	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:145)
    	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:70)
    	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
    	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
    	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
    	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
    	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
    	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
    	at ais.<clinit>(SourceFile:17)

It doesn't work at all with the compact versions - relies on java.awt.  It's built with Java 8, so using JRE 7 is out of the question.

I'm currently performing my own build on an x86 platform, I'll see where that gets me.

**Comment by thirdwheel** [comment]
Update: nope, still get the same error.

**Comment by thirdwheel** [comment]
Just tried a 64-bit build (for which I will send a pull request soonish) aaaaaaand it turns out Minecraft Server requires the server VM - as per your comment on #1.

**Comment by Zlika** [comment]
Hi. As the problem occurs when the VM tries to load a native lib, I suspect this lib to be a 64b lib and then requires a 64b OS and a 64b VM.

**Comment by thirdwheel** [comment]
Which is interesting because I was operating within a 32-bit userland.  Even when I built it in a 32-bit userland I still got that error.
